### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by Spira2025** [jonmbake/bootstrap3-contact-form#11]
Email verification have a fail because if i write some thing is valid. should be if i write mail@mail.net is valid.

**Comment by jonmbake** [comment]
Hey @Spira2025.  When I test that email address in the demo: https://jonbake.com/demos/contact-form/index.html, that email address passes validation.  Are you using Bootstrap Validator, or the provided email validation?

**Comment by Spira2025** [comment]
![screen shot 2016-01-18 at 12 25 14 pm](https://cloud.githubusercontent.com/assets/16746293/12397969/ad05b852-bdde-11e5-81bf-a2759bc2f611.png)
Here your have,

**Comment by Spira2025** [comment]
And still having problems with recaptcha.

**Comment by jonmbake** [comment]
@Spira2025 The little green checkbox is a known issue.  The checkbox indicate that a value has been filled in.  The field is still outlined in red with an error message to indicate an error.  I think this is acceptable.

Usually problems with recaptcha are due to setup with Google.  Are you sure things are set up correctly?    There is also a branch w/o captcha: https://github.com/jonmbake/bootstrap3-contact-form/tree/no-captcha if it becomes too much of a pain.

**Comment by Spira2025** [comment]
Why it frozen on Sending... but success email?

**Comment by jonmbake** [comment]
Hey @Spira2025.  It disables input until a successful response is received from the server.  This prevents a user from submitting the form multiple times.  The server must not be responding with a successful response.

**Comment by Spira2025** [comment]
Possible to implement date jquery?

**Comment by Spira2025** [comment]
Jonmbake how to put on email comes from?
